"""Prepare English merchandising drafts using only explicit source-title attributes.
Unrecognised titles remain in the private handoff; never substitute a generic product.
Run after capture_1688_home.py. No network requests or database writes.
"""
import json, re
from pathlib import Path
from urllib.parse import urlencode
ROOT = Path('/tmp/fotizo-1688-home-2026-10-05')
OUT = Path('docs/sourcing/1688-home-2026-10-05')
CATEGORY = {'pets-garden':'improvement','daily-essentials':'general','hair-styling':'wigs','home-cleaning':'general','computers':'computers','car-accessories':'car','home-appliances':'appliances'}
# Specific product nouns before broad nouns. These are concise source-derived drafts,
# not verified specifications or literal translations of promotional search titles.
RULES = [
('暖菜板|热菜板|饭菜保温板','Food Warming Tray'),('中药壶|熬药锅|煎药壶','Electric Herbal Decoction Pot'),('暖风器|电暖器|小太阳取暖','Electric Heater'),
('除螨仪','Mattress Vacuum Cleaner'),('电蚊拍','Electric Insect Swatter'),('墙暖|电暖气','Electric Wall Heater'),('榨汁杯|果汁机','Portable Blender'),('硅胶刮刀','Silicone Kitchen Scraper'),
('车载椅背小桌|汽车旅行桌','Car Seat Tray Table'),
('浴室刷|缝隙刷|锅刷|竹炊帚','Household Cleaning Brush'),('湿厕纸|湿纸巾','Household Wipes'),('地板净','Floor Cleaner'),('焕新粉|去渍粉','Cleaning Powder'),('厨房清洁系列','Kitchen Cleaning Product'),('温度计|温湿度计','Temperature and Humidity Meter'),('单词本|便签本','Pocket Notebook'),('束裤带|束脚带','Reflective Cycling Bands'),('合页.*调缝|调节门缝','Hinge Adjustment Tool'),('育苗杯|种子杯','Seedling Pots'),('防倒器|防倒扣','Furniture Anti-Tip Fastener'),('平板電腦|tablets','Tablet Computer'),('数字标牌|数码云相框','Digital Display'),('手持终端|工业pda','Industrial Handheld Computer'),('方向盘.*装饰配件','Steering Wheel Decorative Accessory'),('车载摆件','Car Ornament'),('一次性座套|一次性座位套','Disposable Car Seat Covers'),('钥匙包','Car Key Cover'),('汽车香水座','Car Fragrance Holder'),('电机','Electric Motor'),('厨师机|和面机','Stand Mixer'),('瓜果.*净化器','Produce Cleaning Appliance'),('电热炉','Electric Hotplate'),

('海盐.*喷雾','Sea Salt Hair Styling Spray'),('披肩|吹风围布','Salon Cape'),('洗发水','Shampoo'),('精华水|精华液','Cosmetic Serum'),('护指绷带','Finger Protection Wrap'),('凸面反光镜','Convex Safety Mirror'),('游戏指套','Gaming Finger Sleeves'),('干燥剂|干燥条','Desiccant Pack'),('透明肩带','Clear Bra Straps'),('插座保护|插头防护','Socket Safety Cover'),('针线盒|针线包','Sewing Kit'),('防摩擦腿贴','Anti-Chafing Pads'),('水龙头.*钥匙','Tap Key'),('口水巾','Disposable Bib'),('蟑螂屋','Cockroach Trap'),('冷热包|冰袋','Reusable Cooling Pack'),('魔术贴','Hook-and-Loop Fastener'),('提桶器|提水器','Water Container Handle'),('地板保养蜡','Floor Care Wax'),('瓷砖翻新剂','Tile Surface Restorer'),('除垢剂|锅底黑垢去除','Descaling Cleaner'),('自喷漆|乳胶漆','Paint or Paint Cleaning Product'),('泡腾片','Effervescent Cleaning Tablets'),('除尘纸|除尘巾','Dusting Wipes'),('五面刷','Cleaning Brush'),('一体机电脑|台式.*电脑','Desktop Computer'),('轮毂.*修复膏','Wheel Repair Compound'),('驱鼠','Rodent Deterrent'),('制冷剂|冷媒|冰点还原剂','Car Air Conditioning Treatment'),('座椅护理剂','Leather Seat Care Product'),('护膝垫|护腿垫','Car Knee Support Pad'),('导航.*膜|屏幕.*膜|中控.*膜|保护贴膜','Vehicle Screen Protector'),('表板蜡|仪表盘蜡','Dashboard Polish'),('卡片夹|票据收纳夹','Car Document Clip'),('储物网兜|车载挡网','Car Storage Net'),('换挡拨片','Gear Shift Paddles'),('感谢牌','Driver Message Sign'),('钥匙套','Car Key Cover'),('空气清新剂|汽车除臭|香熏|香水夹','Car Air Freshener'),('轮胎泡沫|轮胎蜡','Tyre Dressing'),('排量标','Vehicle Badge'),('大灯翻新|大灯修复','Headlight Restoration Product'),('汽车刮板','Car Window Squeegee'),('车内饰品摆件|车窗.*摆件','Car Interior Ornament'),('流苏挂件','Car Hanging Ornament'),

('定型喷雾|头发喷雾|蓬松水|泡泡胶','Hair Styling Spray'),('多用刷|多功能刷','Multipurpose Cleaning Brush'),('补锅贴','Cookware Repair Patch'),('裤脚.*固定贴|裤腿贴','Clothing Hem Tape'),('空调挡风板|空调遮风板','Air Conditioner Deflector'),('书籍胶|粘书胶|书脊胶','Bookbinding Glue'),('纸巾盒|抽纸盒|抽纸袋','Tissue Holder'),('电话号码牌|停车号码|挪车电话|移车牌','Parking Contact Number Display'),('置物袋|储物袋|座椅背袋','Car Seat Storage Bag'),('门碗|把手贴','Car Door Handle Protection Film'),('缝隙.*塞|缝隙填补','Car Seat Gap Filler'),('遮阳伞|防晒帘','Car Sunshade'),('抽油器|抽油神器','Manual Fluid Transfer Pump'),('塑料件.*翻新','Car Plastic Trim Restorer'),('眼镜夹|票据夹','Car Visor Clip'),('门锁.*缓冲|门锁扣','Car Door Lock Buffer'),('无线充.*垫|充电面板','Car Charging Pad Cover'),('双面胶','Double-Sided Adhesive Tape'),('除胶剂|粘胶去除','Adhesive Remover'),('火山泥|跑泥|搓泥','Car Detailing Clay'),('划痕蜡|刮痕擦痕膏','Car Scratch Repair Compound'),('出风口保护罩','Car Air Vent Cover'),('按钮装饰圈|点火圈','Car Ignition Button Trim'),('开关.*保护盖','Car Switch Cover'),('烟灰缸','Car Ashtray'),('防雾剂','Car Glass Anti-Fog Treatment'),('挂饰|吊饰|车挂|后视镜挂件','Car Hanging Ornament'),('汽车摆件|出风口装饰夹|中控台摆件','Car Interior Ornament'),('装饰贴|贴纸|风口贴|车内饰贴','Decorative Vehicle Trim or Sticker'),('布套.*挡风玻璃','Windscreen Cleaning Cloth Cover'),

('漂粉|褪色粉|漂白粉','Hair Bleaching Powder'),('直发膏|拉直膏|热烫药水','Hair Straightening Treatment'),('弹力素','Curl Styling Cream'),('泡沫发蜡|摩丝','Hair Styling Mousse'),('发蜡|发泥|油头膏','Hair Styling Wax'),('啫喱|发胶|干胶|定型水','Hair Styling Gel or Spray'),('发油','Hair Styling Oil'),('风罩|烘发罩','Hair Dryer Diffuser'),('定位夹|鸭嘴夹|分区.*夹','Hair Sectioning Clips'),
('收纳包','Storage Bag'),('暖棚|温棚|雨棚','Garden Shelter'),('拔草夹|拔除器','Weeding Tool'),('摘果器|拾果器|果实采摘','Fruit Picking Tool'),('草坪平整器','Lawn Levelling Tool'),('水果套袋|保护袋','Fruit Protection Bags'),('漱口杯','Bathroom Rinse Cup'),('牙签|牙缝刷','Interdental Cleaning Picks'),('雨伞罩','Parasol Cover'),('托盘|塑料盘|果盘','Serving Tray'),('冷敷头套|冰敷帽','Cooling Head Wrap'),('脏衣篮|洗衣篮','Laundry Basket'),('过滤棉','Water Filter Cotton'),('沐浴皂|手工皂|洗发.*皂|身粒皂','Cleansing Soap'),('收纳筐|整理盒','Storage Organiser'),('洗手液','Hand Wash'),('耳塞','Earplugs'),('肩垫|肩贴','Clothing Shoulder Pads'),('袖套|护袖','Protective Sleeve Covers'),('推拉杆','Window Opening Pole'),('密封胶泥|堵塞泥','Sealing Putty'),('吸汗贴','Underarm Sweat Pads'),('地漏|下水器|漏水塞','Drain Accessory'),('面罩','Face Shield'),('咖啡杯|牛奶杯|马克杯|玻璃杯|燕麦杯','Drinking Cup'),('储物罐|密封罐','Storage Jar'),('耳贴|护耳贴','Waterproof Ear Covers'),('别针|收腰扣','Clothing Adjustment Pin'),('脚后跟保护|护脚套','Heel Protector'),('门塞|门档|门阻','Door Stop'),('锅盖.*把手|锅盖.*手柄','Pan Lid Handle'),('百洁布','Scouring Pad'),('清洁膏|护理膏|去污膏','Surface Cleaning Paste'),('清洁粉|除渍粉|泡泡乐','Cleaning Powder'),('纱窗洗','Window Screen Cleaner'),('家庭清洁.*礼盒','Household Cleaning Gift Set'),('工业平板','Industrial Tablet'),('工控机|计算机','Industrial Computer'),('屏幕保护套','Vehicle Screen Cover'),('油膜去除','Car Glass Cleaner'),('缝隙塞条','Car Seat Gap Filler'),('刮水板|水刮板','Car Window Squeegee'),('汽车贴纸|车贴','Vehicle Decorative Stickers'),('出风口夹.*装饰|内饰摆件|中控摆件','Car Interior Ornament'),('润滑剂','Vehicle Lubricant'),('轮胎刷','Tyre Cleaning Brush'),('轮毂修复膏|抛光膏','Car Polishing Compound'),

('堆肥|蚯蚓塔','Garden Composter'),('育苗盒|育苗保温罩|育苗养护罩','Seedling Propagation Container'),('定植板|洞洞板|育苗板|定植洞洞','Plant Mounting Board'),('水培器皿|水竹篮|净化篮|种植篮','Hydroponic Plant Basket'),('工具套装|工具六件套|工具 6 件套|养花专用工具','Gardening Tool Set'),('树干保护|树干防护','Tree Trunk Guard'),('植物防寒罩|植物罩|幼苗保护|育苗保护|蔬菜保护','Plant Protection Cover'),('洒水器','Garden Sprinkler'),('滴水套件|滴灌|浇花器','Plant Watering Kit'),('铺路模具','Paving Stone Mould'),('冲水器','Portable Electric Water Sprayer'),('喷水枪|喷雾器|喷枪','Garden Sprayer'),('自动喂水|爬虫水盆','Reptile Water Bowl'),('底砂|流沙|石子|鹅卵石|雨花石|溪流石|铺底石','Decorative Aquarium Gravel'),('植物架|植物固定架','Plant Support'),('塑钢线|托幕线','Greenhouse Support Line'),('种植托盘|园艺地垫|换土垫|拌土垫|种植垫','Potting Mat'),('躲避|晒台','Reptile Hide or Basking Platform'),('补光灯','Plant Grow Light'),('基质','Plant Growing Medium'),('园艺剪|修枝剪|修果剪|葡萄剪|修剪.*剪|花木剪','Pruning Shears'),('夜光石|荧光石|发光石','Glow Decorative Stones'),('温室|暖房|阳光房','Garden Greenhouse'),('造景|微景观|盆景.*摆件','Aquarium or Garden Ornament'),('打孔器','Soil Planting Tool'),('铲|耙|锄','Gardening Hand Tool'),('驱鸟器','Bird Deterrent Device'),('发芽盆|育苗托盘','Seed Sprouting Tray'),('笼子|宠物笼|昆虫笼','Animal Enclosure'),('消毒剂|消毒粉|消毒液','Disinfectant'),('粘虫板|虫粘板','Sticky Insect Trap'),('工具包','Tool Bag'),('植物.*固定夹','Plant Support Clips'),('花篮','Flower Basket'),('镊子','Long Tweezers'),('沉木|杜鹃根','Decorative Driftwood'),

('防猫刺|驱猫钉','Cat Deterrent Mat'),('地钉|地插钉|草坪钉','Garden Ground Staples'),('无头钉|圆钢钉|铁钉','Steel Nails'),
('椰砖|椰糠','Coco Coir Growing Medium'),('松树皮|松磷','Pine Bark Growing Medium'),('火山石','Lava Rock Granules'),('除草剂','Garden Weed Treatment'),
('育苗罩','Seedling Cover'),('育苗盘','Seedling Tray'),('攀爬架|支撑架|爬藤架|花支架','Plant Support'),('园艺扎线|绑扎带|绑花|花艺铁丝','Garden Plant Ties'),
('宠物纪念|纪念牌','Pet Memorial Plaque'),('仿真|假花','Artificial Decorative Plant'),('猫砂盆','Cat Litter Tray'),('猫砂','Cat Litter'),('猫爬架','Cat Tree'),('猫抓','Cat Scratcher'),('狗绳|牵引绳','Pet Lead'),('宠物窝|猫窝|狗窝','Pet Bed'),('宠物碗|猫碗|狗碗','Pet Bowl'),('宠物玩具|猫玩具|狗玩具','Pet Toy'),
('浇水壶|浇花壶|淋花壶|洒水壶','Watering Can'),('喷壶|喷雾瓶','Spray Bottle'),('喷雾头|喷头','Spray Nozzle'),('花盆','Plant Pot'),('营养土','Potting Medium'),
('马桶刷|厕所刷','Toilet Brush'),('马桶|洁厕|蓝泡泡','Toilet Cleaner'),('牙刷','Toothbrush'),('牙线','Dental Floss'),('牙膏','Toothpaste'),
('地板刷|地刷','Floor Scrubbing Brush'),('玻璃刷|擦窗器','Window Cleaning Tool'),('抹布|洗碗巾|茶巾|清洁巾','Cleaning Cloth'),('湿巾','Cleaning Wipes'),('垃圾袋','Bin Bags'),('垃圾桶','Waste Bin'),
('灭烛|聪明盖','Candle Snuffer Lid'),('海绵擦|清洁海绵|木浆棉','Cleaning Sponge'),('干发帽','Hair Drying Towel Wrap'),('浴帽','Shower Cap'),('皮筋|发圈|头绳','Hair Ties'),('发夹','Hair Clip'),('热缩膜|热缩袋','Shrink Wrap Bags'),
('除霉','Mould Stain Cleaner'),('除黄|去黄','Yellowing Stain Cleaner'),('除锈','Rust Stain Cleaner'),('地毯清洁|沙发.*清洗','Upholstery Cleaner'),('地板清洁|拖地.*清洁','Floor Cleaner'),('石材|大理石','Stone Surface Cleaner'),('瓷砖缝隙','Tile Grout Cleaner'),('瓷砖.*清洗|瓷砖.*清洁','Tile Cleaner'),('冰箱.*清洁|厨电清洁','Appliance Cleaner'),('浴室.*清洁|水垢.*清洁|浴室.*喷雾','Bathroom Cleaner'),('清洁泡腾片|清洁.*泡腾片','Effervescent Cleaning Tablets'),('清洁乳','Cleaning Cream'),('清洁剂|清洗剂|清洁液|清洗液|清洁喷雾|去污剂','Cleaning Solution'),
('扫把|扫帚|笤帚','Broom'),('拖把','Mop'),('除尘掸|鸡毛掸','Duster'),('清洁刷|除尘刷|风扇刷|床刷|毛刷','Cleaning Brush'),
('平板电脑|智能平板|安卓平板|数码平板|学习平板|平板学习机','Tablet Computer'),('笔记本电脑|手提电脑|轻薄本|游戏本|掌上.*电脑','Laptop Computer'),('笔记本|白纸本','Notebook'),('鼠标垫','Mouse Mat'),('鼠标','Computer Mouse'),('键盘','Computer Keyboard'),('电脑支架|笔记本支架','Laptop Stand'),('电脑包','Laptop Bag'),('显示器','Computer Monitor'),('固态硬盘|移动硬盘','Computer Storage Drive'),('扩展坞','USB Hub'),('数据线','Charging Cable'),('充电器','Charger'),('耳机','Headphones'),('音箱','Speaker'),
('车载椅背小桌|汽车旅行桌','Car Seat Tray Table'),('后备箱.*收纳|后备箱.*储物|汽车收纳箱|车载收纳箱|车载收纳盒','Car Boot Organiser'),('方向盘.*挂钩|车载挂钩','Car Hook'),('门碗贴|把手膜','Car Door Handle Protection Film'),('头枕|腰靠|腰托|颈枕','Car Support Cushion'),('清洁软胶|清洁泥|清洁胶','Cleaning Gel'),('魔泥手套|磨泥手套|粘土手套','Car Detailing Clay Mitt'),('国旗|红旗摆件','Car Flag Ornament'),('遮雪挡|防雪罩|车罩|车衣','Car Cover'),('应急启动','Car Jump Starter'),('充气泵','Tyre Inflator'),('镀晶海绵|打蜡.*海绵|海绵块','Car Detailing Sponge'),('排档|档把|挡把','Gear Lever Trim'),('抬头显示保护|hud','Head-Up Display Cover'),('挡风玻璃.*刷|挡风玻璃.*擦|除雾刷','Windscreen Cleaning Tool'),('香薰|香膏','Fragrance Accessory'),('汽车挂件|车载挂件|后视镜.*吊坠','Car Hanging Ornament'),('手机.*支架|磁吸支架','Phone Mount'),('防撞条|防擦条|防撞贴','Car Protection Strip'),('反光条|反光贴','Reflective Vehicle Stickers'),('安全带','Seat Belt Accessory'),('遮阳挡|遮阳帘|遮阳板','Car Sunshade'),('脚垫','Car Floor Mat'),('方向盘套','Steering Wheel Cover'),('雨刮','Wiper Accessory'),('坐垫|座垫|座椅套','Seat Cover'),
('吹风机|电吹风','Hair Dryer'),('卷发棒|卷发器','Hair Curler'),('直发器|直板夹|夹板','Hair Straightener'),('理发器|电推剪','Hair Clipper'),('理发剪|美发剪','Hairdressing Scissors'),('假发','Wig'),('梳子|梳','Hair Comb'),('烫发','Hair Styling Tool'),
('电饭煲|电饭锅','Rice Cooker'),('空气炸锅','Air Fryer'),('电热水壶|电水壶|烧水壶','Electric Kettle'),('电磁炉','Induction Hob'),('电陶炉','Electric Ceramic Hob'),('电煮锅|电火锅|电炒锅|电热锅','Electric Cooking Pot'),('破壁机|料理机|榨汁机','Blender'),('咖啡机','Coffee Maker'),('豆浆机','Soy Milk Maker'),('绞肉机','Food Chopper'),('打蛋器','Electric Whisk'),('面包机|多士炉','Bread Appliance'),('电饼铛','Electric Griddle'),('电烤箱|烤箱','Electric Oven'),('三明治机','Sandwich Maker'),('华夫饼机','Waffle Maker'),('电蒸锅','Electric Steamer'),('养生壶','Electric Tea Pot'),('煮蛋器','Egg Cooker'),
('吸尘器','Vacuum Cleaner'),('扫地机器人','Robot Vacuum'),('洗衣机','Washing Machine'),('烘干机|干衣机','Clothes Dryer'),('挂烫机|熨斗','Garment Steamer or Iron'),('电风扇|循环扇|落地扇|风扇','Electric Fan'),('加湿器','Humidifier'),('除湿机','Dehumidifier'),('空气净化器','Air Purifier'),('取暖器|暖风机','Electric Heater'),('电冰箱|冰箱','Refrigerator'),('饮水机','Water Dispenser'),('净水器','Water Filter Appliance'),('剃须刀','Electric Shaver'),('脱毛器','Hair Removal Device'),('毛球修剪器','Fabric Shaver'),('洗鞋机','Shoe Washer'),('烘鞋器|干鞋器','Shoe Dryer'),('制冰机','Ice Maker'),
('水杯|塑料杯|保温杯','Drinking Cup'),('水桶','Bucket'),('挂钩','Storage Hook'),('置物架|收纳架','Storage Rack'),('收纳盒|储物盒','Storage Box'),('收纳袋','Storage Bag'),('毛巾','Towel'),('围裙','Apron'),('手套','Gloves'),('瓶','Bottle')
]
ATTRS = [('不锈钢','Stainless Steel'),('超细纤维','Microfibre'),('牛津布','Oxford Fabric'),('硅胶','Silicone'),('塑料','Plastic'),('折叠','Foldable'),('伸缩','Telescopic'),('软毛','Soft Bristle'),('长柄','Long Handle'),('便携','Portable'),('可调节','Adjustable')]
def prepare():
 OUT.mkdir(parents=True,exist_ok=True); products={};coverage=[]
 for key in CATEGORY:
  d=json.loads((ROOT/f'{key}-crawl.json').read_text());coverage.append({**{k:v for k,v in d.items() if k!='products'},'complete':len(d['pages'])==50 and not any(p['error'] for p in d['pages']),'searchUrl':'https://www.1688.com/zw/page.html?'+urlencode({'hpageId':'old-sem-pc-list','keywords':d['query']})})
  for r in d['products']:
   ident=r['productId']
   if ident in products:
    if key not in products[ident]['sourceCategories']: products[ident]['sourceCategories'].append(key)
    continue
   t=r['originalTitle'].lower(); kind=next((v for k,v in RULES if re.search(k,t)),None)
   if ident in {'908829025216','868400111329','860814303722','847452274143'}:kind='Refillable Spray Bottle'  # Individual source photos visually reviewed.
   cat=CATEGORY[key]
   if kind=='Electric Motor':cat='industrial'
   held = key=='daily-essentials' and bool(re.search('滴眼|洗眼|滴鼻|明目液|穴位|矫正器|舒缓膏|膏贴|乳膏|软膏|皮肤|止痒|瘙痒|生理盐水|洗鼻|秋梨膏|雪梨膏|舒缓贴|八横膏|苦甲水|冷敷喷|舒肤膏|氨糖|艾柱|祛螨|鼻撑|鼻孔支撑',t))
   if key=='pets-garden' and re.search('宠物|猫|狗|鱼缸|水族|乌龟',t) and not re.search('跨境宠物及园艺',t):cat='pets'
   if kind=='Notebook':cat='office'
   attrs=[v for k,v in ATTRS if re.search(k,t)]
   screen_sizes = list(dict.fromkeys(re.findall(r'(?<![\d.])(\d{1,2}(?:\.\d+)?)\s*(?:英寸|寸|inch)',t))) if kind in {'Tablet Computer','Laptop Computer','Computer Monitor','Digital Display','Industrial Tablet'} else []
   capacities = list(dict.fromkeys(re.findall(r'(?<![\d.])(\d+(?:\.\d+)?\s*(?:ml|l))(?=[^a-z]|$)',t))) if kind in {'Electric Kettle','Rice Cooker','Air Fryer','Electric Cooking Pot','Spray Bottle','Stand Mixer','Drinking Cup','Watering Can','Portable Blender'} else []
   title_parts = ([screen_sizes[0]+'-inch'] if len(screen_sizes)==1 else []) + (['Android'] if kind=='Tablet Computer' and re.search('安卓|android',t) else []) + ([capacities[0].upper()] if len(capacities)==1 else [])
   title=' '.join(title_parts+attrs[:2]+[kind]) if kind else None
   specs=[{'label':'Product type','value':kind}] if kind else []
   if screen_sizes:specs.append({'label':'Listed screen sizes','value':', '.join(screen_sizes)+' inches; confirm the selected model'})
   if capacities:specs.append({'label':'Listed capacities','value':', '.join(capacities)+'; confirm the selected model'})
   if attrs:specs.append({'label':'Listed features','value':', '.join(attrs)})
   desc=f'{title}. '+ ('Listed features: '+', '.join(a.lower() for a in attrs)+'. ' if attrs else '')+'Confirm the selected model, dimensions and included items before ordering.' if title else None
   products[ident]={**r,'sourceCategories':[key],'proposedCategory':cat,'englishTitle':title,'englishDescription':desc,'specifications':specs,'translationStatus':'source-derived-english-draft' if title else 'pending','publishable':False,'reviewHold':'outside-household-merchandising-scope' if held else None}
 (OUT/'products.json').write_text(json.dumps(list(products.values()),ensure_ascii=False,indent=2)+'\n')
 (OUT/'coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2)+'\n')
 unmatched=[r for r in products.values() if not r['englishTitle']]
 (OUT/'unmatched-titles.json').write_text(json.dumps([{'id':r['productId'],'title':r['originalTitle']} for r in unmatched],ensure_ascii=False,indent=2)+'\n')
 print('Captured',len(products),'English drafts',len(products)-len(unmatched),'unmatched',len(unmatched))
if __name__=='__main__':prepare()
